type Skill = {
    title: string;
    level: 1 | 2 | 3;
    category: "Dev" | "DevOps" | "Soft";
};

export default [
    { title: "NodeJS", level: 3, category: "Dev" },
    { title: "Typescript", level: 3, category: "Dev" },
    { title: "React", level: 3, category: "Dev" },
    { title: "Redux", level: 3, category: "Dev" },
    { title: "Mobx", level: 3, category: "Dev" },
    { title: "Zustand", level: 3, category: "Dev" },
    { title: "Zod", level: 3, category: "Dev" },
    { title: "Yup", level: 3, category: "Dev" },
    { title: "Formik", level: 3, category: "Dev" },
    { title: "ExpressJS", level: 3, category: "Dev" },
    { title: "Vite", level: 3, category: "Dev" },
    { title: "TSOA", level: 3, category: "Dev" },
    { title: "Class-transformer/Validator", level: 3, category: "Dev" },
    { title: "TypeORM", level: 3, category: "Dev" },
    { title: "Sequelize", level: 3, category: "Dev" },
    { title: "NextJS", level: 3, category: "Dev" },
    { title: "NestJS", level: 2, category: "Dev" },
    { title: "Javascript", level: 3, category: "Dev" },
    { title: "Websocket", level: 3, category: "Dev" },
    { title: "Promises/Async", level: 3, category: "Dev" },
    { title: "HTML", level: 3, category: "Dev" },
    { title: "CSS/SASS/SCSS", level: 3, category: "Dev" },
    { title: "Python", level: 3, category: "Dev" },
    { title: "Asyncio", level: 3, category: "Dev" },
    { title: "FastAPI", level: 3, category: "Dev" },
    { title: "Django/DRF", level: 3, category: "Dev" },
    { title: "SQL", level: 3, category: "Dev" },
    { title: "Postgres", level: 3, category: "Dev" },
    { title: "Redis", level: 2, category: "Dev" },
    { title: "Git", level: 3, category: "DevOps" },
    { title: "Docker", level: 3, category: "DevOps" },
    { title: "PM2", level: 3, category: "DevOps" },
    { title: "Linux", level: 3, category: "DevOps" },
    { title: "Bash", level: 2, category: "DevOps" },
    { title: "MySQL", level: 2, category: "Dev" },
    { title: "NoSQL", level: 2, category: "Dev" },
    { title: "MongoDB", level: 2, category: "Dev" },
    { title: "NGINX", level: 2, category: "DevOps" },
    { title: "CI/CD", level: 2, category: "DevOps" },
    { title: "InfoSec", level: 2, category: "DevOps" },
    { title: "Golang", level: 1, category: "Dev" },
    { title: "C/C++", level: 1, category: "Dev" },
    { title: "Apache", level: 1, category: "DevOps" },
    { title: "System design", level: 3, category: "Soft" },
    { title: "Team management", level: 2, category: "Soft" },
    { title: "Technical writing", level: 2, category: "Soft" },
    { title: "Technical communication", level: 2, category: "Soft" },
    { title: "English", level: 2, category: "Soft" },
    { title: "Japanese", level: 1, category: "Soft" },
].sort((skillA, skillB) => skillB.level - skillA.level) as Skill[];
